### ISSUE TITLE
Home page project list only displays 1 project, should display 3

### ISSUE THREAD

**Issue by alecmakeus** [SquaredLabs/squaredlabs.uconn.edu#103] opened 2018-06-02 18:40 UTC

**Comment by ColinMcNeil** [comment] 2018-06-02 21:33
It only displays the projects order 1, 2, and 3. There are no projects with label 2 or 3 because I was testing. I recommend going on the CMS and checking out the "order" attribute

**Comment by ColinMcNeil** [comment] 2018-06-05 16:38
I'm closing this because it is not a bug. I will assign 2 projects so you can see all 3.

**Closed by ColinMcNeil** 2018-06-05 16:38 UTC
Labels: bug, help wanted
